version: "3.7"

services:
    mongo:
        container_name: mongo
        image: mongo:4-xenial
        ports:
            - 27017:27017
        networks:
            - java-network
    redis:
        container_name: redis
        image: redis:5
        ports: 
            - 6379:6379
        networks:
            - java-network
    java-docker:
        container_name: java-docker
        image: thingswise/java-docker
        ports:
            - 8080:8080
        depends_on:
            - redis 
            - mongo
        environment:
            - NAME=docker
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks:
            - java-network

networks:
    java-network:
        name: java-network